---


- name: Configure Lifecycle Transition
  hosts: resource
  gather_facts: False
  become: true

  tasks:
  
  - name: copy myuac.xml
    copy:
      src: ./config/myuac.xml
      dest: /

  - name: create pythonmonitor
    file: 
      path: /pythonmonitor
      state: directory

  - name: copy monitor.py
    template:
      src: ./config/monitor.py
      dest: /pythonmonitor

  - name: create /etc/collectd
    file: 
      path: /etc/collectd
      state: directory

  - name: copy collectd.conf
    template:
      src: ./config/collectd.conf
      dest: /etc/collectd/

  - name: add kafka.lm to hosts
    become: yes
    shell: "echo {{ dl_properties.almip }} kafka.lm >> /etc/hosts"
